# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8fc26c790031ca6a5ce5d3120b35d29052300ec8a7d60276f175b1bc3e2b4d85bfd88a734c5fb659b14ae8a72862b082ad493d48e4da42d787d8e6b43785522

test:
  secret_key_base: 18695d4e64da9379fda40f60ed79df1755c823b5f1d708bd6cb40aa5f6b9cd7fc5fc2e0859c23b9c7ab6771271bcc3189c734c3d34a4b90628e0e99f7b20ea1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
